# Generated by Django 6.0.1 on 2026-02-07 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_lecturer_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='home.lecturer'),
        ),
    ]
