# Generated by Django 6.0.1 on 2026-02-07 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_lecturer_code_alter_review_lecturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='tags',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.lecturer'),
        ),
        migrations.AddField(
            model_name='review',
            name='subjects',
            field=models.ManyToManyField(to='home.subject'),
        ),
    ]
