# Generated by Django 6.0.1 on 2026-02-08 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_subject_review_tags_alter_lecturer_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='subject_studied',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='review',
            name='suitable_for',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='campus',
            field=models.CharField(default='ĐÀ NẴNG', max_length=50),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='home.lecturer'),
        ),
        migrations.AlterField(
            model_name='review',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='home.subject'),
        ),
        migrations.AlterField(
            model_name='review',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
