# Generated by Django 6.0.1 on 2026-02-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_add_review_subject_studied_suitable_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='subjects_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
