# Generated by Django 6.0.1 on 2026-02-12 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_restaurant_place_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LivingPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('distance', models.CharField(blank=True, max_length=100)),
                ('price_avg', models.FloatField(default=0)),
                ('location_avg', models.FloatField(default=0)),
                ('amenity_avg', models.FloatField(default=0)),
                ('security_avg', models.FloatField(default=0)),
                ('overall_score', models.FloatField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LivingComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('price', models.IntegerField()),
                ('location', models.IntegerField()),
                ('amenity', models.IntegerField()),
                ('security', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('living_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.livingplace')),
            ],
            options={
                'unique_together': {('living_place', 'user')},
            },
        ),
        migrations.CreateModel(
            name='LivingCommentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='living_comment_images/')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.livingcomment')),
            ],
        ),
    ]
